begin
  fail 'An error!'
rescue => e
  puts e.message
end
